// Supabase Edge Function — `ai-hint`
//
// POST /functions/v1/ai-hint
//   Headers: Authorization: Bearer <user JWT>
//   Body:    { "problem_id": "<uuid>", "level": 1 | 2 | 3 }
//   200:     { hint, remaining_today }
//   429:     { error: "QUOTA_EXCEEDED", remaining_today: 0 }
//   503:     { error: "MISSING_API_KEY" }   — until GROQ_API_KEY is set
//   400/500: { error: "..." }
//
// Notes:
//   - Backed by Groq + Llama 3.3 70B (free tier: 30 RPM / 6 000 TPM,
//     no card required, no region restrictions). Get a key at
//     https://console.groq.com and store it as a Supabase Edge secret
//     named `GROQ_API_KEY`.
//   - Groq exposes an OpenAI-compatible API, so swapping providers later
//     to OpenAI / Together / OpenRouter is just a base-URL + model swap.
//   - The function reads the *full* problem row, including `expected_answer`,
//     using a service-role client. It NEVER returns the answer to the
//     student — only a level-specific hint generated by the model.
//   - Daily quota = 10 successful (and inserted) requests in the last 24h
//     per `user_id`. Tweak `DAILY_QUOTA` below.

// @ts-expect-error — Deno std URL import, resolved at runtime by the Edge runtime
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.39.7";
import { corsHeaders } from "../_shared/cors.ts";

declare const Deno: {
  env: { get(name: string): string | undefined };
  serve: (handler: (req: Request) => Promise<Response> | Response) => void;
};

const DAILY_QUOTA = 10;
const MODEL = "llama-3.3-70b-versatile";
const GROQ_URL = "https://api.groq.com/openai/v1/chat/completions";

interface RequestBody {
  problem_id: string;
  level: 1 | 2 | 3;
}

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...corsHeaders, "content-type": "application/json" },
  });

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  if (req.method !== "POST") return json({ error: "METHOD_NOT_ALLOWED" }, 405);

  let body: RequestBody;
  try {
    body = (await req.json()) as RequestBody;
  } catch {
    return json({ error: "BAD_REQUEST" }, 400);
  }
  if (
    !body?.problem_id ||
    typeof body.problem_id !== "string" ||
    !Number.isInteger(body.level) ||
    body.level < 1 ||
    body.level > 3
  ) {
    return json({ error: "BAD_REQUEST" }, 400);
  }

  // Identify caller via JWT.
  const authHeader = req.headers.get("Authorization") ?? "";
  const supabaseUrl = Deno.env.get("SUPABASE_URL");
  const anonKey = Deno.env.get("SUPABASE_ANON_KEY");
  const serviceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");
  if (!supabaseUrl || !serviceKey || !anonKey) return json({ error: "SERVER_MISCONFIGURED" }, 500);

  // Brief trace so 401s are diagnosable from the function logs without
  // leaking the full token. Logs only the algorithm prefix + length.
  console.log(
    `[ai-hint] auth header len=${authHeader.length} prefix=${authHeader.slice(0, 12)} starts_with_bearer=${authHeader.toLowerCase().startsWith("bearer ")}`,
  );

  const userClient = createClient(supabaseUrl, anonKey, {
    global: { headers: { Authorization: authHeader } },
  });
  const { data: userData, error: userErr } = await userClient.auth.getUser();
  if (userErr || !userData?.user) {
    console.log(`[ai-hint] auth failed: ${userErr?.message ?? "no user"}`);
    return json({ error: "UNAUTHORIZED" }, 401);
  }
  const userId = userData.user.id;

  const admin = createClient(supabaseUrl, serviceKey);

  // 1) Quota check.
  const dayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
  const quotaRes = await admin
    .from("ai_hints")
    .select("id", { count: "exact", head: true })
    .eq("user_id", userId)
    .gte("created_at", dayAgo);
  if (quotaRes.error) return json({ error: "DB_ERROR" }, 500);
  const usedToday = quotaRes.count ?? 0;
  if (usedToday >= DAILY_QUOTA) {
    return json({ error: "QUOTA_EXCEEDED", remaining_today: 0 }, 429);
  }

  // 2) Load problem (service-role bypasses RLS so we can read expected_answer).
  const probRes = await admin
    .from("problems")
    .select("id, problem_text_kz, expected_answer, unit, difficulty")
    .eq("id", body.problem_id)
    .maybeSingle();
  if (probRes.error || !probRes.data) return json({ error: "PROBLEM_NOT_FOUND" }, 404);
  const problem = probRes.data as {
    id: string;
    problem_text_kz: string;
    expected_answer: string | null;
    unit: string | null;
    difficulty: number;
  };

  // 3) Groq call (OpenAI-compatible chat completions).
  const apiKey = Deno.env.get("GROQ_API_KEY");
  if (!apiKey) {
    return json({ error: "MISSING_API_KEY" }, 503);
  }

  const { systemPrompt, userPrompt } = buildPrompts(problem, body.level);

  const upstream = await fetch(GROQ_URL, {
    method: "POST",
    headers: {
      "content-type": "application/json",
      authorization: `Bearer ${apiKey}`,
    },
    body: JSON.stringify({
      model: MODEL,
      messages: [
        { role: "system", content: systemPrompt },
        { role: "user", content: userPrompt },
      ],
      temperature: 0.4,
      max_tokens: 600,
    }),
  });

  if (!upstream.ok) {
    const errText = await upstream.text();
    console.error(`groq ${upstream.status}: ${errText}`);
    return json({ error: "UPSTREAM" }, 502);
  }

  type GroqResponse = {
    choices?: Array<{ message?: { content?: string } }>;
    usage?: { prompt_tokens?: number; completion_tokens?: number };
  };
  const payload = (await upstream.json()) as GroqResponse;
  const hintText = (payload.choices?.[0]?.message?.content ?? "").trim();

  if (!hintText) return json({ error: "EMPTY_RESPONSE" }, 502);

  // 4) Persist for audit + future quota counts.
  const insertRes = await admin.from("ai_hints").insert({
    user_id: userId,
    problem_id: problem.id,
    level: body.level,
    response_text: hintText.slice(0, 8000),
    model: MODEL,
    tokens_input: payload.usage?.prompt_tokens ?? null,
    tokens_output: payload.usage?.completion_tokens ?? null,
  });
  if (insertRes.error) {
    console.error("insert ai_hints failed", insertRes.error);
    // Still return the hint to the user — we don't want to penalise them
    // for an internal logging failure.
  }

  return json({ hint: hintText, remaining_today: Math.max(0, DAILY_QUOTA - usedToday - 1) }, 200);
});

function buildPrompts(
  p: { problem_text_kz: string; expected_answer: string | null; unit: string | null },
  level: 1 | 2 | 3,
): { systemPrompt: string; userPrompt: string } {
  const systemPrompt = [
    "Сен — атомдық және молекулалық физика курсындағы шыдамды репетиторсың.",
    "Қазақ тілінде жауап бер. Жауапты өзі емес, бағыт-сілтемемен бер.",
    "ҚАТАҢ ЕРЕЖЕ: ешқашан есептің соңғы сандық жауабын тікелей айтпа.",
    "Формулалар үшін LaTeX-ты $...$ немесе $$...$$ ішінде қолдан, KaTeX рендері қосылған.",
    "Жауапты қысқа, нақты, 2-3 параграфтан аспайтындай ұста.",
  ].join(" ");

  const expectedHint = p.expected_answer
    ? `\n\n[ҚҰПИЯ КОНТЕКСТ — ОҚУШЫҒА КӨРСЕТПЕ] Дұрыс жауап: ${p.expected_answer}${p.unit ? " " + p.unit : ""}.`
    : "";

  const taskBase = `Есеп: ${p.problem_text_kz}${expectedHint}`;
  let userPrompt = "";
  if (level === 1) {
    userPrompt = [
      taskBase,
      "Деңгей 1: Қай физикалық заң немесе ұғым осында қолданылады? 1 параграфпен түсіндір.",
      "Формула жазба, сандарды қолданба.",
    ].join("\n\n");
  } else if (level === 2) {
    userPrompt = [
      taskBase,
      "Деңгей 2: Қажетті формуланы LaTeX-та көрсет, әр айнымалысын аз сөзбен сипатта.",
      "Шарттан қандай мәндер берілгенін атап өт. Сандарды формулаға қойма.",
    ].join("\n\n");
  } else {
    userPrompt = [
      taskBase,
      "Деңгей 3: Қадамдап шешуді көрсет, бірақ ҮЗ-ҮЗ соңғы сандық есептеудің алдында тоқта.",
      "Студенттен соңғы санды өзі есептеуін сұра. Дұрыс жауапты ешқашан өзің жазба.",
    ].join("\n\n");
  }
  return { systemPrompt, userPrompt };
}
